import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Box } from '@mui/material';
import SidebarDrawer from '../components/SidebarDrawer';
import { flexColumn } from '@/theme/sharedStyle';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function PageLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Box sx={{ ...flexColumn, flexGrow: 1 }}>
      <SidebarDrawer />
      {children}
    </Box>
  );
}
