import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { DeviceProvider } from './context/DeviceTypeContext';
import ThemeRegistry from '@/theme/ThemeRegistry';
import { AuthContextProvider } from './context/AuthContext';
import { flexColumn, linearGradient } from '@/theme/sharedStyle';
import { green } from '@/theme/colors';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={inter.className}
        style={{
          display: 'flex',
          flexDirection: 'column',
          minHeight: '100vh',
          background: linearGradient(green.primary, 'white'),
        }}
      >
        <ThemeRegistry options={{ key: 'mui' }}>
          <DeviceProvider>
            <AuthContextProvider>{children}</AuthContextProvider>
          </DeviceProvider>
        </ThemeRegistry>
      </body>
    </html>
  );
}
